### ISSUE TITLE
FR: Reopen site in container

### ISSUE THREAD

**Issue by rafamel** [cmcode-dev/firefox-containers-helper#31]
I would like to propose that the ability to **reopen the site in the current tab** in another container is added to the add-on.

Great work!

**Comment by cmcode-dev** [comment]
Hi @rafamel! Thanks for creating this issue :smile: 

I'll put this on the roadmap! It's a great idea.

**Comment by cmcode-dev** [comment]
![image](https://user-images.githubusercontent.com/97761753/166475288-e4d388bd-aef3-42e2-b029-b13989f20a0e.png)

Here's a preview.

**Comment by cmcode-dev** [comment]
This has been implemented and released in v0.0.24. Thanks for requesting the feature! I will also find it useful myself in the future :slightly_smiling_face:  https://addons.mozilla.org/en-US/firefox/addon/containers-helper/versions/

**Comment by rafamel** [comment]
Hello @cmcode-dev, thanks so much for being open to the feedback and implementing this! A great extension made even better!
