### ISSUE TITLE
Hello I love the IDEA of this add on however it's being a nightmare for me.

### ISSUE THREAD

**Issue by DavidH888** [cmcode-dev/firefox-containers-helper#32]

**Comment by DavidH888** [comment]
I have many YouTube channels and was TRYING to use the add on to automatically open different channels in different containers but that doesn't work AT ALL.
NOW when I open Youtube it says there is an OOPS EVERY TIME. Youtube won't open AT ALL unless I open it in a container. It doesn't matter which container but it's completely arbitrary because I have no ability to SELECT a container anymore. I made the mistake of selecting a default for youtube at first but now it opens based ONLY on the prior container that was open. Also EVERY TIME I restart my computer or open my browser ANY tab that had been opened to this or that channel or page in youtube will be an OOPS and will open a NEW TAB and FORCE me to select a container but not give me the choice of the 15 containers I have created instead offering me two container options with no abililty to see or select any other options or containers. 

I can't find a way to get back to default and now Youtube won't open at all UNLESS it's in a container.

HELP.

I disabled the add on but the problem persists.

Great idea though. Can you tell me how to reset WITHOUT having to reset Firefox because I have A LOT of add ons installed and it takes A LONG TIME TO GET BACK TO HERE and I'm in a "time crisis" right now.

Thanks

**Comment by cmcode-dev** [comment]
Hey @DavidH888 , I'm looking over your post now.

**Comment by cmcode-dev** [comment]
Hmm, it almost sounds like this is an issue with the built-in Multi-Account Containers addon from Mozilla, not my extension.

**Comment by cmcode-dev** [comment]
Generally when you've assigned a site to open in a specific container, it will only prompt you to open it in either a the same container or the container you've assigned it in. The Containers Helper extension doesn't have any control over this.

I would love to help you debug it if possible. Are you available on any platform to chat?

**Comment by DavidH888** [comment]
Yes that's what it's doing. SAME CONTAINER though turns out to be NO container, which fails every time. The contianer is different depending on the container that was LAST assigned. Neither is what I need and the EMPTY, No container isn't even an option any more.

**Comment by DavidH888** [comment]
I'm open to it. Walk me through it.

**Comment by cmcode-dev** [comment]
Ok. Post a screenshot of the page you're talking about.

**Comment by DavidH888** [comment]
wow that's a surprise. I just reenabled container helper and now it's opening every page in the container I had opened it in. Clearly the issue was not your add on and I'm very happy about that because yours seems to be the most useful of the ones I've tried.

Is there a way to get different youtube channels to open in different containers? Because ON YOUTUBE if I open to the library it just says
https://www.youtube.com/feed/library

There doesn't seem to be a way for your add on to differentiate which channel I happen to be logged into which is ironically the main reason for containers in the first place.

**Comment by cmcode-dev** [comment]
Here's a quick video of what I _think_ might have been causing your issue, and how to fix it:

https://user-images.githubusercontent.com/97761753/160031698-9001178f-f294-4a88-a961-cd69979fcad4.mp4

**Comment by DavidH888** [comment]
![image](https://user-images.githubusercontent.com/59571482/160031784-4d7dc007-5589-4b19-b429-1104d330185e.png)

OOPS, just got the oops page when I tried the link I sent youj to my feed. Just was curious what page it accessed since I didn't look which page I took it from.

**Comment by cmcode-dev** [comment]
> wow that's a surprise. I just reenabled container helper and now it's opening every page in the container I had opened it in. Clearly the issue was not your add on and I'm very happy about that because yours seems to be the most useful of the ones I've tried.

Well, I'm glad to hear that!

> Is there a way to get different youtube channels to open in different containers? Because ON YOUTUBE if I open to the library it just says

There's no _automatic_ way to do this. You'll need to name your containers according to their YouTube channels, and then use the keyboard shortcut to bring up the popup menu, and then filter on each container's name when you want that specific channel/container.

Think of it as training your muscle memory to open the Firefox Containers Helper instead of using the URL bar to get to your channel+container combo.

**Comment by DavidH888** [comment]
how can I remove the Default page I sellected. If I can't select a different one for each channel I prefer to choise each time.

**Comment by cmcode-dev** [comment]
> how can I remove the Default page I sellected. If I can't select a different one for each channel I prefer to choise each time.

In the video I posted above, you will see me right click -> multi account containers -> "Always open in this container". Make sure to _un-check_ that.

**Comment by DavidH888** [comment]
chuckle. I've done that. 15 channels, 15 Containers.
It's not ideal but the best I've come up with so far. I was HOPING there was container tools that would make things a little easier.

**Comment by cmcode-dev** [comment]
I gotcha. With a slight tweak in your muscle memory, it'll be as fast as any other method. I'm not sure there is any way to automatically figure out which container should be launched without introspecting the current YouTube session/cookies, and that's way out of scope for this extension! :sweat_smile:

**Comment by DavidH888** [comment]
smile. Ok. thanks for your help and I love the extension anyway.
unfortunatelyt for me I can onlty access 10 with a direct ctrl+shift 1...0 excecution.
